#!/usr/bin/env node

const fs = require("fs");
const processor = require("./processor.js");
const { exec } = require("child_process");

// Create a file
// Optional path

function program() {
  const args = processor.filterArgs(process.argv);
  const commands = processor.filterCommands(args);
  const options = processor.filterOptions(args);
  return {
    getFilePath() {
      this.path = processor.getPath(args);
      return this;
    },
    getFileName() {
      this.fileName = processor.getFileName(args);
      return this;
    },
    get fullPath() {
      return this.path + "/" + this.fileName;
    },
    writeFile() {
      if (!this.fileName || !this.path) {
        this.path = "/Users/Theo/Desktop/playground";
        this.fileName = "playground.js";
      }

      fs.mkdir(this.path, err => {
        fs.writeFile(
          `${this.path}/${this.fileName}`,
          "// Generated by playjs",
          error => {
            if (error) throw error;
            console.log(`File written @ ${this.fullPath} `);
            exec(`cd ${this.path} && npm init -y && open . && open ${this.fileName}`, err => {
              if (err) console.log(err)
            });
          }
        );
      });
    }
  };
}

program()
  .getFilePath()
  .getFileName()
  .writeFile();
